### ISSUE TITLE
CORS errors

### ISSUE THREAD

**Issue by jeremydrichardson** [ghostops/ICloud-Shared-Album#1]
I'm getting CORS errors when trying to use this library with my React app.

I would expect this to be the case but wanted to check if perhaps Apple shared albums didn't have CORS setup when you first built this.

I tested from Node which avoids CORS, and it worked great. Unless I'm missing something and you have a way that it will work directly, I'm thinking to setup a serverless (lambda perhaps) function that can handle the requests and cache the photos for use.

Thanks for a great library

**Comment by ghostops** [comment]
Yes Apple has CORS, and I probably haven't specified that the library is intended for serverside use. Will add that in the readme 😄 .  Lambda-functions would be a great use-case for this, so I suggest you go that route.

Thanks for contributing with the feedback!
