### ISSUE TITLE
Videos not downloading on full size

### ISSUE THREAD

**Issue by alandooz** [ghostops/ICloud-Shared-Album#5]
When downloading videos, the derivatives has two sizes, for example 640 and 1280.

On the 640 I have the mp4, but on the 1280 I only had like the first frame of the video, or the frame that shows the preview, on jpg, but not the mp4.

Is this a bug? Is it possible to have the url of the video on full size instead of just the jpg (and maybe have the jpg for both sizes also, apart from the video)?

**Comment by ghostops** [comment]
Hi! Thanks for creating the issue. I have never tried uploading a video to an album, so this never occurred to me. I have made it so that duplicate derivatives will look like this:

```typescript
derivatives: {
  '720': {
    checksum: 'string',
    fileSize: 1000,
    width: 50,
    height: 720,
    url: 'https://...',
  },
  '720-1': {
    checksum: 'string',
    fileSize: 5000,
    width: 500,
    height: 720,
    url: 'https://...',
  },
  '720-2': {
    checksum: 'string',
    fileSize: 10000,
    width: 5000,
    height: 720,
    url: 'https://...',
  }
}
```

Which will make it so that you actually get all versions of the file back in the response. 😄

**Comment by alandooz** [comment]
@ghostops you're really amazing! Thankss
