### ISSUE TITLE
HTTP error 330 (redirect) - I will submit a PR for this

### ISSUE THREAD

**Issue by jmaton** [ghostops/ICloud-Shared-Album#6]
Sometime this year (2024) Apple broke this project with 330 redirect.
@bertrandom fixed it in https://github.com/bertrandom/icloud-shared-album-to-flickr
so I adapted his fix to fit your wonderful project.  (Big thanks to both of you.)

I will submit the PR.

**Comment by ghostops** [comment]
Thank you very much for contributing 🙏
